<?php echo $this->doctype() ?>
<html xmlns="http://www.w3.org/1990/xhtml">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>SPC - Standard Password Checker</title>
    <?php echo $this->headLink()->appendStylesheet('/SPC/spc/public/css/global.css') ?>
</head>
<body>
    <header>
        <h1>SPC</h1>
        <h2><span class="initial">S</span>tandard <span class="initial">P</span>assword <span class="initial">C</span>hecker</h2>
    </header>
    <article>
        <?php echo $this->layout()->content ?>
    </article>
    <footer>
    	<nav>
    		<ul>
            	<li><a href="<?php echo $this->url(array('controller' => 'index'), 'default', true) ?>">Home</a></li>
            	<li><a href="<?php echo $this->url(array('controller' => 'check'), 'default', true) ?>">Check list</a></li>
        	</ul>
    	</nav>
    </footer>
</body>
</html>
